name: CI Tests

on:
  workflow_dispatch:
    inputs:
      test_level:
        description: 'Escolha o nível de teste a rodar'
        required: true
        default: 'unit'
        type: choice
        options: 
          - unit
          - integration
          - e2e

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run selected tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        if [ "${{ github.event.inputs.test_level }}" == "unit" ]; then
          pytest -s tests/unit --junitxml=report.xml
        elif [ "${{ github.event.inputs.test_level }}" == "integration" ]; then
          pytest -s tests/integration --junitxml=integration-report.xml
        else
          pytest -s tests/e2e --junitxml=e2e-report.xml
        fi

